// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/data': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/data').default>>>>
    }
    '/api/istilahData': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/istilahData').default>>>>
    }
    '/api/mukayese': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mukayese.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}