// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/15/2025, 4:14:03 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/yunustalhacoban/Desktop/mutalaa/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yunustalhacoban/Desktop/mutalaa/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yunustalhacoban/Desktop/mutalaa/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yunustalhacoban/Desktop/mutalaa/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yunustalhacoban/Desktop/mutalaa/plugins/**/*.{js,ts,mjs}","/Users/yunustalhacoban/Desktop/mutalaa/composables/**/*.{js,ts,mjs}","/Users/yunustalhacoban/Desktop/mutalaa/utils/**/*.{js,ts,mjs}","/Users/yunustalhacoban/Desktop/mutalaa/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yunustalhacoban/Desktop/mutalaa/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/yunustalhacoban/Desktop/mutalaa/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/yunustalhacoban/Desktop/mutalaa/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;